### ISSUE TITLE
Segmentation fault on game launch

### ISSUE THREAD

**Issue by notargets** [juzzlin/DustRacing2D#1]
I installed version 1.11.0 from the AUR under Manjaro Linux. When I run `dustrac-game` from a terminal, I get the following output:

```
[Thu Apr 30 23:24:47 2015] I: Dust Racing 2D version 1.11.0
[Thu Apr 30 23:24:47 2015] I: Compiled against Qt version 5.4.1
[Thu Apr 30 23:24:47 2015] I: Failed to load translations for C
[Thu Apr 30 23:24:47 2015] I: Creating game object..
[Thu Apr 30 23:24:47 2015] I: Resolution: 1920 1080 1
[Thu Apr 30 23:24:47 2015] I: Creating the renderer..
[Thu Apr 30 23:24:48 2015] I: OpenGL Version: 3.0 Mesa 10.5.3
[Thu Apr 30 23:24:48 2015] I: Loading font ./data/fonts/UbuntuMono-R.ttf..
QIODevice::read: device not open
[Thu Apr 30 23:24:48 2015] W: Failed to load font ./data/fonts/UbuntuMono-R.ttf..
[Thu Apr 30 23:24:48 2015] I: Loading font ./data/fonts/UbuntuMono-B.ttf..
QIODevice::read: device not open
[Thu Apr 30 23:24:48 2015] W: Failed to load font ./data/fonts/UbuntuMono-B.ttf..
[Thu Apr 30 23:24:48 2015] I: Font texture size: 240x960                                                                                                        
[Thu Apr 30 23:24:48 2015] I: Loading surface config from './data/surfaces.conf'..                                                                              
[Thu Apr 30 23:24:48 2015] F: Parsing './data/surfaces.conf' failed!                                                                                            
[Thu Apr 30 23:24:48 2015] F: Initializing the game failed!                                                                                                     
Segmentation fault (core dumped)
```

**Comment by juzzlin** [comment]
I suspect that the AUR packaging is somehow broken, because the data files cannot be read. The segmentation fault eventually happens because the game cannot read ./data/surfaces.conf. According to the log it seems that also loading the font files fails. Of course the segmentation fault on initialization error is another bug, but not a reason for this failure. The data paths used in the packaging might be incorrect, because it tries to open ./data/surfaces.com and not for example /usr/share/dustrac/data/surfaces.conf. I don't know anything about Arch so I don't know how it should be done.

**Comment by juzzlin** [comment]
I'm closing this issue, because I'm not the maintainer of the AUR package so I cannot do anything about this.

**Comment by reynaldo666** [comment]
I could ran this game only from the same directory it was compiled. I got the same issue in any other directory. I compiled from source (./configure && make && sudo make install). Maybe ./data/surfaces.conf would be something like $PATH/data/surfaces.conf.
Please reconsider this issue.

**Comment by juzzlin** [comment]
Yes, that's the default development mode. Linux packaging and local installs should use the release build (ReleaseBuild=ON) and define data location with -DDATA_PATH define. See the end of INSTALL documentation and InstallLinux.cmake.

**Comment by juzzlin** [comment]
One clarification: the development build doesn't care where the game is compiled. It can be started from any directory, only the data directory must be copied into the same directory with the game binary. The release build tries to find data files according to -DDATA_PATH.

**Comment by reynaldo666** [comment]
Oh, thanks! 
It worked in my notebook, but it has poor graphics (radeon xpress 1150). Now I'm trying to build for Ubuntu precise amd64.

**Comment by juzzlin** [comment]
I'm not sure but the default Qt in Ubuntu 12.04 might be too old. I'm using 14.04 and 15.04 myself.

**Comment by reynaldo666** [comment]
I had upgraded to 14.04 and it worked. Ty
