### ISSUE TITLE
Car sometimes crashes into bridge when driving over bridge at very high speed

### ISSUE THREAD

**Issue by Wuzzy2** [juzzlin/DustRacing2D#10]
Version: 4ab15830293395db4560fa9f5d9bbef733f43930
OS: GNU/Linux

If you drive very fast over a bridge (>150 km/h or so), you sometimes crash even before you got onto the bridge. If you then go in reserve and then try to pass the bridge again, you can drive over the bridge.
Very weird bug, I also cannot reproduce it 100%.

**Comment by juzzlin** [comment]
I've also noticed similar problems with the bridge. I suspect that the car collides with side walls at the lower level before it's detected to be on the bridge.
