### ISSUE TITLE
Media license question

### ISSUE THREAD

**Issue by Wuzzy2** [juzzlin/DustRacing2D#107]
Quote from the README:

> All image files, except where otherwise noted, are licensed under CC BY-SA 3.0: http://creativecommons.org/licenses/by-sa/3.0/

What are the “otherwise” cases? Are there any proprietary media files (meaning, they are not Free Cultural Works https://freedomdefined.org/Definition), and if yes, which ones?

**Comment by juzzlin** [comment]
I cannot think of any. Maybe there was at some point, but they have been later on replaced with my own worse graphics.

**Comment by Wuzzy2** [comment]
Good, thanks.
