### ISSUE TITLE
Problematic license of Ubuntu font

### ISSUE THREAD

**Issue by pinotree** [juzzlin/DustRacing2D#24]
Currently (as of 1.13.0) Dist Racing 2D embeds a copy of the Ubuntu fonts in `data/fonts`; they were added with commit 2c9fc33818bffefc452443eb3a48f0138f93cf85, used in commit cd8203eaf16e244f8ae7b49c0bfbe1c8af4ed672 (so since version 1.6.1).

While working on getting Dust Racing 2D packaged for Debian, I spotted this detail, and a related discussion related to the packaging of the Ubuntu font for Debian: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=603157 ("main"  there refers to the "main" section of the Debian archive, where all the software complies with the DFSG [1] -- in particular, https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=603157#30 (by one of the Debian FTP-Masters, i.e. the group accepts/removes packages from the Debian archive, among the other things).
Long story short, the Ubuntu font is deemed non-free, because:
- the preferred form of modification is a data file of a Commercial software (which alone would still allow the font as part of the "contrib" section of the Debian archive)
- issues with the license itself

On top of this, the license of the Ubuntu font is not mentioned anywere in the sources, and the license itself [2] requires its text to be provided with the font:

> 1. Each copy of the Font Software must contain the above copyright notice and this licence. These can be included either as stand-alone text files, human-readable headers or in the appropriate machine-readable metadata fields within text or binary files as long as those fields can be easily viewed by the user.

(This could be fixed easily by including a full copy of the license, next to the fonts.)

Thus my request is to switch away from the Ubuntu font, and either not enforce any particular monospaced font (relying on the system default font), or use a free font (for example DejaVu [3], widely available in distributions).

[1] https://www.debian.org/social_contract.en.html#guidelines
[2] http://font.ubuntu.com/licence/
[3] https://dejavu-fonts.github.io/

**Comment by juzzlin** [comment]
I'm already experimenting with another fonts. Do you think we could use for example this (licence-wise):
https://www.1001freefonts.com/molot.font

The author (http://www.jovanny.ru/faq/) says here: "All fonts from the “Free fonts” section can be used both for personal and commercial purposes without any limitations."

The problem with the "standard" fonts is that they usually don't look nice in games. I also want the game to look exactly the same on all platforms, that's why the font is bundled with the game. 

For now I'll add the Ubuntu font licence. Thanks!

**Comment by pinotree** [comment]
> I'm already experimenting with another fonts. Do you think we could use for example this (licence-wise):
https://www.1001freefonts.com/molot.font
> 
> The author (http://www.jovanny.ru/faq/) says here: "All fonts from the “Free fonts” section can be used both for personal and commercial purposes without any limitations."

I do not find any license with this, and the above text (found only in the FAQs) does not make the font free, since it does not specify whether you can modify the font, for example.

> The problem with the "standard" fonts is that they usually don't look nice in games. I also want the game to look exactly the same on all platforms, that's why the font is bundled with the game.

Bundling is not a problem, if the font is a standard one (I can replace the font files with symlinks to the system locations of the fonts).
I suggested DejaVu, because it is used by many games: 0ad, freeciv, gnubg, megaglest, neverball, pokerth, teeworlds, warmux, wesnoth, openmw, and more (on Debian/Ubuntu, see the result of `apt-cache rdepends fonts-dejavu-core`).  Another reason is that DejaVu has a much better coverage of glyphs, so there is no worry for languages with non-latin scripts.

**Comment by juzzlin** [comment]
You are right about the glyph coverage. I'll experiment with DejaVu a bit.

**Comment by juzzlin** [comment]
The font is now changed to DejaVu in the (currently very unstable) development branch so in the next release Ubuntu font will be gone.

**Comment by juzzlin** [comment]
Fixed in 2.0.0

**Comment by pinotree** [comment]
Thanks a lot!

Easy enough to replace in Debian packaging to use the system copy.
