### ISSUE TITLE
A minimap would be greatly appreciated

### ISSUE THREAD

**Issue by mquinson** [juzzlin/DustRacing2D#3]
As the title says, the game is a bit hard to play if you don't know perfectly the track you're racing on. A minimap would be greatly improve the usability.

Thanks for that great game,
Mt

**Comment by juzzlin** [comment]
I agree that a minimap would be great. That's quite a bit of work, though :)

**Comment by reynaldo666** [comment]
I agree.

**Comment by juzzlin** [comment]
I'm finally working on this now :)

**Comment by reynaldo666** [comment]
Cool! Thanks!

**Comment by juzzlin** [comment]
There's now a first version of the minimap in the master branch. I think it turned out to be pretty awesome and definitely makes the game better! :)

**Comment by mquinson** [comment]
That's really really cool, many thanks for that.
