### ISSUE TITLE
Dual Player Mode: key-press not recognized

### ISSUE THREAD

**Issue by KarlZeilhofer** [juzzlin/DustRacing2D#42]
when playing in dual player mode, sometimes key presses are not recognized. It seems, that the inputs are limited to max. 4 keys simultaneously. 

Can this anyone reproduce, or is this an issue with my hardware? Old Samsung 410B notebook, running Linux Mint 19 with Qt5.9, self compiled.

**Comment by juzzlin** [comment]
I believe this is a hardware limitation. At least we cannot do anything about it with the current implementation :)
