### ISSUE TITLE
Black screen after start - Win7, Nvidia

### ISSUE THREAD

**Issue by rhinolophus** [juzzlin/DustRacing2D#44]
I'm having the same issue as previously reported #30. However I'm running version 2.0.0, which was released before the aforesaid issue was opened, on Win7 x64 and latest Nvidia drivers 430.86.
The game itself seems to be running (sound and everything) but it's all black except of a happy little tree.
[![screenshot](http://img18105.imagevenue.com/loc145/th_699884266_dustrac2_win7_nvidia_122_145lo.jpg)](http://img18105.imagevenue.com/img.php?image=699884266_dustrac2_win7_nvidia_122_145lo.jpg)
So if that issue is fixed already could you please provide compiled binaries for Windows?
Version 1.13.0 works fine though.

**Comment by juzzlin** [comment]
Hi, 

Could you try if this works for you:

[dustracing2d-2.0.2-windows-x86-qt5_setup.zip](https://github.com/juzzlin/DustRacing2D/files/3294361/dustracing2d-2.0.2-windows-x86-qt5_setup.zip)

**Comment by rhinolophus** [comment]
Yes, it works. Awesome.
Thanks for the quick reply.

**Comment by juzzlin** [comment]
Ok, cool :) I think I'll then make a new release soon.
