### ISSUE TITLE
Question about image licensing

### ISSUE THREAD

**Issue by Wuzzy2** [juzzlin/DustRacing2D#45]
In the README it says “All image files, except where otherwise noted, are licensed under CC BY-SA 3.0: http://creativecommons.org/licenses/by-sa/3.0/”

What are the “otherwise” cases? Is there actually any image on an other license, because I can't find any.

**Comment by juzzlin** [comment]
Not that I know of.

**Comment by Wuzzy2** [comment]
So can you then please delete this “otherwise noted”? It seems misleading.
