### ISSUE TITLE
Walls and grandstands are pushable

### ISSUE THREAD

**Issue by Wuzzy2** [juzzlin/DustRacing2D#48]
In many tracks, the grandstands and walls are pushable.

This can mess up the tracks quite badly on long races in which the cars crash into walls all the time. It's not good when you end up with entire wall blocks lying around on the road. :D

I think these objects should always be immobile, no exceptions. Many of my previous map contributions rely on these objects being immobile.

This is a regression, in earlier versions, grandstands and walls were immovable. I think these objects always need to be immobile, no exceptions.

Tested in version: 2.0.1

**Comment by juzzlin** [comment]
This is by design, but maybe the objects are now too light.

**Comment by Wuzzy2** [comment]
The levels I contributed pretty much relied on these objects being immovable. Especially Radiator. Just play a race with 10 laps. Eventually the road gets littered badly.

I also think the idea of pushing a grandstand to the road is kind of hilarious … and sad. xD

**Comment by juzzlin** [comment]
I'll test that tomorrow. Btw, you can force things stationary in the editor. Right-click on an object => Force stationary.

**Comment by Wuzzy2** [comment]
I have tested latest dev version again. Now it seems to be much better. It seems the walls now can't be pushed at all in Radiator and other levels. Grandstands are still pushable, but they are extremely hard to push now, so they will probably no longer litter the race track.

Good.

I close this issue now.
