### ISSUE TITLE
Change custom track directory

### ISSUE THREAD

**Issue by Wuzzy2** [juzzlin/DustRacing2D#49]
If you create a custom track, the game forces you to use ~/DustRacingTracks as directory. This is pretty annoying as it pollutes the home directory. This is mainly a problem on GNU/Linux or BSD.

I suggest to use the XDG basedir specification:

https://standards.freedesktop.org/basedir-spec/basedir-spec-latest.html

For this game, it would boil down to:

* Read the environment variable `$XDG_DATA_HOME`
* If the environment variable exists, read tracks from `$XDG_DATA_HOME/DustRacing2D/tracks`
* If `$XDG_DATA_HOME` does not exist, look into `$HOME/.local/share/DustRacing2D/tracks`

For compability, the game could still additionally read from `~/DustRacingTracks`, but it shall be considered deprecated.

**Comment by juzzlin** [comment]
Reasonable, although `$HOME/.local/share/DustRacing2D/tracks` seems to even more annoying. My Ubuntu 19.04 doesn't set `$XDG_DATA_HOME`. I can make this change.

What do you think of adding a CLI parameter (e.g. `--add-track-path`) that would add search paths?

**Comment by Wuzzy2** [comment]
I say “annoying” because the directory is *visible*. But directories with a period at the beginning will be hidden.

This is pretty standard practice on GNU/Linux.

I think adding a command line parameter seems to be a bit overkill, but if you really want it, eh, whatever.

**Comment by juzzlin** [comment]
I know how directories work on Linux. I just don't want that my tracks are in some hidden magic directory I eventually forget about.

**Comment by juzzlin** [comment]
Fixed in cb270f639e44078f88c9e1aa66cb0bbedbcfedd3

Thanks for reporting!
