### ISSUE TITLE
Menu transition is slow when selecting difficulty and laps

### ISSUE THREAD

**Issue by Wuzzy2** [juzzlin/DustRacing2D#64]
If I select the difficulty and the laps, the time it takes for the new menu to appear is noticable long. It's a few seconds sometimes, but it should be instant. This does not take the animation into account.

Version: 2.0.3

Maybe this is related to #2.

**Comment by juzzlin** [comment]
This happens only sometimes? Sounds weird. I haven't ever seen slow performance in the menu.

**Comment by Wuzzy2** [comment]
When I delete my `Game.conf`, it is fast again. My current `Game.conf` currently has ca. 400 lines (I have played this game quite a bit recently, a lot of unlocked tracks in various lap counts, saved records, etc. …). Maybe the reading of this file is just slow. Maybe?

**Comment by juzzlin** [comment]
It shouldn't be **that** slow, but it could be evaluated many times. I didn't find that kind of a bug in those menus, however. Fixed a possible problem in track selection menu.
