### ISSUE TITLE
Editor displays legacy track path on startup

### ISSUE THREAD

**Issue by Wuzzy2** [juzzlin/DustRacing2D#66]
As of 2.0.3, the editor still shows the legacy track path (`~/DustRacingTracks`) in the startup message.

As I understand, this game now supports a different path for custom tracks, see #49. It just seems to display the legacy path only.

**Comment by juzzlin** [comment]
Fixed in 2a99c6018be5283ca98d64ca2f0c84c619da302d. This was a bit tricky to fix without breaking all existing translations.
