### ISSUE TITLE
Cars teleport above and below bridges when driving horizontally in Radiator

### ISSUE THREAD

**Issue by Wuzzy2** [juzzlin/DustRacing2D#69]
If you drive on the Radiator track on the bridges (horizontally), your car will teleport above and below the bridge all the time, instead of staying above the bridge. You can still complete the track normally, but your car will look like it flashes “on and off” and it will occassionally collide with cars that drive vertically (below the bridges).

Version: 61ada1e8db21c1a38f0ec69a1dbcc94d8333caed

**Comment by juzzlin** [comment]
Yes, the current "bridge" is shit and needs to be rewritten. It has now this bug when there are multiple sequential bridges touching each other.

**Comment by juzzlin** [comment]
Finally fixed in f31d8b468b7ffedf22685c165d5a0070fd3cd918. Thanks for reporting!
