### ISSUE TITLE
Bad track preview images

### ISSUE THREAD

**Issue by Wuzzy2** [juzzlin/DustRacing2D#7]
In 4ab15830293395db4560fa9f5d9bbef733f43930, the trackpreview images look kinda broken and ugly.
Screenshot:
https://i.imgur.com/hkPUb2X.png

It looks like some vertical lines got somehow messed up:

**Comment by juzzlin** [comment]
This happened due to incorrect texture clamping.

**Comment by akien-mga** [comment]
Great to this this fixed, I had noticed it too but somehow was too lazy to file a bug report back then on SourceForge. I'm glad the repo is now on GitHub, it's way easier to file issues and make PRs.
