### ISSUE TITLE
Confusing starting numbers in two player mode

### ISSUE THREAD

**Issue by Wuzzy2** [juzzlin/DustRacing2D#71]
In the game modes “two player race” and “duel”, the players have the starting numbers 1 and 11, which is a bit confusing.

I suggest the following:

When playing in two player race or duel, do:
* Use start number 1 for player 1
* Use start number 2 for player 2

**Comment by juzzlin** [comment]
Fixed in 61f7c1e4fc4b641568ef2d7f5d38d5822bb1565e. Thanks for reporting!
