### ISSUE TITLE
Apostrophe character is broken

### ISSUE THREAD

**Issue by Wuzzy2** [juzzlin/DustRacing2D#72]
In version 2.0.3, the apostrophe character (U+0027) currently is broken. If it is displayed in the game, a weird garbled mess is shown in place of the character.
Only a few languages (German and French) currently use the apostrophe character. In French, it's used e.g. in the help. In German, it's for the translation of “Better luck next time”. Note that it's the ASCII apostrophe, so this character should definitely work.

How to reproduce:
* Set language to French
* Start game
* Go into help
* The apostrophe in “l'ordinateur” is a garbled mess

**Comment by juzzlin** [comment]
Fixed in master. Thanks for reporting!
