### ISSUE TITLE
Twister track has no pit stop

### ISSUE THREAD

**Issue by Wuzzy2** [juzzlin/DustRacing2D#74]
In 2.0.3, the Twister track has no pit stop.

This will be a problem in races with a high number of laps.

**Comment by Wuzzy2** [comment]
Here's something that could be inserted into `twister.trk`:

```
<o x="937" y="1984" o="0" r="pit" c="free"/>
```

(for commit 02235fb0679713853e306117a2e86ac61caeddc1)

**Comment by juzzlin** [comment]
Seemed good, thanks!
