### ISSUE TITLE
Roughly sort tracks by length/complexity/difficulty

### ISSUE THREAD

**Issue by Wuzzy2** [juzzlin/DustRacing2D#75]
I think the current ordering of the tracks isn't very good. The difficulty, length and complexity of the tracks is currently all over the place. A good track order matters because of unlocking.

I propose to put short/simple/easy tracks at the beginning while moving long/complex/hard tracks more to the end.

Here is a particular order I propose (in brackets: track length, my race record w/ 20 laps, my rationale)

1. Ring (411, 4:08. Certainly the simplest and easiest track in the game. Is a good start.)
2. Infinity (501, 5:19. Also very easy.)
3. Figure 8 (473, 5:30. A beginner's classic.)
4. Triangle (410, 4:35. Only a few simple curves, but the walls and litter lying around can be a bit painful.)
5. Diamond (678, 6:00. Very simple but faster than the previous tracks.)
6. Monza (978, 9:21. Much longer than Diamond but low complexity)
7. Twister (301, 4:51. Very short but many sharp turns.)
8. Suzuka (595, 8:16. Higher complexity, sharper turns but still doable. Has many “guard rails” to help you stay on track.)
9. Western Valley (663, 8:19. Similar to Suzuka, lacks most “guard rails”, allowing you to fly off the track. Has one particular tricky section)
10. Straight (915, 7:56. Surprisingly difficult to master because of the very high speed followed by 180° turns. I tend to fail often here. You need good reaction)
11. Twineburg (737, 9:32. Various tricky turns and a nasty sand pit at the end)
12. Crossroads (1007, 11:46. This position is purely for the length.)
13. Curvastone (1115, 13:01. Because of the section with the 180° turns)
14. Desert Storm (1087, 16:03, Rather technical track with only 90° turns)
15. Far Lands (2110, 20:12. Not neccessarly hard, but the longest track and has a very fast section.)
16. Radiator (873, 12:02. Quite esoteric and technical track, therefore last. Has the most 180° turns of all tracks and the track as a whole can be quite punishing. Needs a lot of concentration to master.)

Feel free to discuss.

**Comment by juzzlin** [comment]
Yes, I like this. The best thing would be to have some heuristics that would automatically decide the "difficulty" order based on track length and maybe amount of curves.

**Comment by Wuzzy2** [comment]
Adding a deliberate sorting algorithm might be a bit overkill at this point for only 16 tracks.

There are many things that contribute to a track's difficulty, and not all are obvious. Think about objects.

**Comment by juzzlin** [comment]
You're right on that one. However, I feel that sorting the tracks by (length * curves) would almost yield your list :)

**Comment by juzzlin** [comment]
What would you think of removing the current index property and adding "difficulty" (e.g. 1-5) value to the editor and tracks?

**Comment by Wuzzy2** [comment]
And how would that work?
Sort by difficulty? With 16 tracks there's gonna be a few dupes. How would you sort the dupes?

**Comment by juzzlin** [comment]
Yes, sort by "difficulty" instead of index. The index thing is a bit irritating if you want to insert in the middle of the existing tracks. Of course we'd loose some resolution depending on the scale. I don't know...maybe it's not a good idea.

**Comment by Wuzzy2** [comment]
I agree, track index is bad. Ideally, this should be outsourced in a separate text file instead of each track file itself. The tracks themselves should not “know” in which position they are.

I'm still a friend of a simple predefined sorting. It Just Works(TM). :P

**Comment by juzzlin** [comment]
A separate sorting file is actually a good idea and probably simple enough to implement.

**Comment by Wuzzy2** [comment]
Fixed by #99.
