### ISSUE TITLE
Dirt particles appear even when not moving on grass

### ISSUE THREAD

**Issue by Wuzzy2** [juzzlin/DustRacing2D#76]
If you stand with your car on grass, dirt particles will constantly appear. They appear all the time, no matter how fast or slow you are. If you're not moving at all, they still spawn at a high rate. It looks very odd and your non-moving car is covered in dirt particles.

Version: 02235fb0679713853e306117a2e86ac61caeddc1

**Comment by juzzlin** [comment]
This was a nice regression bug, thanks for reporting! I just hope I didn't break things even more by fixing this.

**Comment by Wuzzy2** [comment]
Ok, this works now, but IMO could be more tweaked. The particles only stop when the car is at a near full-stop. Even when the car just moves very slightly, the full particle effect appears.

Not really important, however.

**Comment by juzzlin** [comment]
I improved this further in f593aebf03c2aa4671090a725be9c04fa2b15744. Not perfect, but behaves a bit better.

**Comment by Wuzzy2** [comment]
Yeah, it's a bit better now. :)
