### ISSUE TITLE
Pressing accelerate and brake at same time gives weird results

### ISSUE THREAD

**Issue by Wuzzy2** [juzzlin/DustRacing2D#77]
If you hold down accelerate pressed, then hold brake pressed at the same time, then release accelerate, you will still speed up and the brake fails to activate.
If you hold down brake pressed (so that the reverse gear triggers and you go backwards), then also hold down accelerate pressed, then release brake, you will continue to go backwards and the acceleration fails to activate.

This behaviour caused me to fail several times in Straight. I tried to brake, but my car ran with full speed into the map bounds.

Version: 02235fb0679713853e306117a2e86ac61caeddc1

**Comment by juzzlin** [comment]
Seems that I always either accelerate or brake so I haven't noticed this before :)

**Comment by juzzlin** [comment]
Please test if 3875480ac6c0562059d0c3c5d39bac069c6b3e20 fixes the issue.

**Comment by Wuzzy2** [comment]
Tested. Looks good.
:+1:
