### ISSUE TITLE
Confusing/weird stars

### ISSUE THREAD

**Issue by Wuzzy2** [juzzlin/DustRacing2D#8]
Do the stars in the track selection have any meaning?

It seems they are kinda dependent on the best position, but why are there only 10?

Also, I get 10 stars if I only finish 2nd, and I get 1 star for finishing last (12th). This does not seem right.

I use 4ab15830293395db4560fa9f5d9bbef733f43930 on GNU/Linux.

**Comment by juzzlin** [comment]
They represent the best position, but the projection to 10 stars seems to be a bit confusing currently. I thought that 12 stars could be a bit overwhelming, but maybe that would be the best way to fix this.

**Comment by Wuzzy2** [comment]
I think the biggest problem is that 1st and 2nd positions award you the same number of stars.

Suggestion:

1st: 10 stars
2nd: 9 stars
3rd: 8 stars
4th: 7 stars
5th: 6 stars
6th: 5 stars
7th: 4 stars
8th: 3 stars
9th: 2 stars
10th: 1 star
11th or worse: 0 stars

**Comment by juzzlin** [comment]
Yeah, this could be defined like you suggest.

**Comment by juzzlin** [comment]
Fixed in 3aaf91cf6a1421e979a03d15ebdfa7d45c0d5673
