### ISSUE TITLE
Editor segfaults when undoing a change on the last row/column which got deleted before

### ISSUE THREAD

**Issue by Wuzzy2** [juzzlin/DustRacing2D#9]
As of 4ab15830293395db4560fa9f5d9bbef733f43930, the editor crashes with a segmantation fault under this scenario:
- Create new track
- Change some tiles on the bottom row
- Delete the last row
- Now click on “undo”

Boom, the editor segfaults!

Also, in general the editor seems to be pretty selective on what it permits to undo. :-/

**Comment by juzzlin** [comment]
Yeah, IIRC the current undo feature was a 3rd party contribution. It would have been a big task to implement proper undo functionality and didn't want to turn this project into a level editor project :p

**Comment by juzzlin** [comment]
This is now fixed in the master branch. I implemented a universal undo stack that allows almost everything to be undone/redone.
