### ISSUE TITLE
Time Trials don't work, dustrac just exits

### ISSUE THREAD

**Issue by Korodny** [juzzlin/DustRacing2D#95]
I go to settings, switch game mode to time trial, back to main menu with ESC, then try to start a race (Infinity track) - the game just exists. Here's the console output:

`[Fri May  1 17:54:45 2020] <I> Time Trial selected.`
`[Fri May  1 17:54:49 2020] <I> Easy selected.`
`[Fri May  1 17:54:51 2020] <I> 5 laps selected.`
`[Fri May  1 17:54:52 2020] <F> vector::_M_range_check: __n (which is 1) >= this->size() (which is 1)`
`[Fri May  1 17:54:52 2020] <F> Initializing the game failed!`

**Comment by Korodny** [comment]
sry, forgot: dustrac 2.0.5 on Debian Testing.

**Comment by juzzlin** [comment]
Shit, seems so! Thanks for reporting!

**Comment by juzzlin** [comment]
Fixed in 8722d43e4158c2b87b94676b0365266e2eda11ea
